### ISSUE TITLE
Latest version 1.0.1 has a syntax error and will not run

### ISSUE THREAD

**Issue by jontansey** [recharts/react-smooth#28]
Can be seen using npm run kit here 
https://npm.runkit.com/react-smooth

from our build 

```

D:\\node_modules\react-smooth\lib\index.js:1
--
02-Oct-2018 16:15:29 | ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import Animate from './Animate';
02-Oct-2018 16:15:29 | ^^^^^^
02-Oct-2018 16:15:29 |  
02-Oct-2018 16:15:29 | SyntaxError: Unexpected token import
02-Oct-2018 16:15:29 |  
02-Oct-2018 16:15:29 | at transformAndBuildScript (node_modules\jest-runtime\build\transform.js:321:12)
02-Oct-2018 16:15:29 | at Object.<anonymous> (node_modules\recharts\lib\component\Tooltip.js:12:20)
02-Oct-2018 16:15:29 | at Object.<anonymous> (node_modules\recharts\lib\index.js:291:40)


```

**Comment by simonransom-dan** [comment]
We are also seeing errors with 1.0.1 as follows (we are pulling in via recharts@1.3.1):

```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/react-smooth/lib/Animate.js
Only one default export allowed per module.:
export default Animate;
at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)
```

**Comment by LittleColin** [comment]
We are also seeing errors with 1.0.1 as follows (we are pulling in via recharts@1.3.1):

```
Errors prevented bundling:
While minifying app code:
packages/minifyStdJS/plugin/minify-js.js:96:26: Babili minification error
within packages/modules.js:
node_modules/react-smooth/lib/Animate.js
Only one default export allowed per module.:
export default Animate;
at maybeThrowMinifyErrorBySourceFile
(packages/minifyStdJS/plugin/minify-js.js:96:26)
at files.forEach.file (packages/minifyStdJS/plugin/minify-js.js:135:9)
at Array.forEach (<anonymous>)
at MeteorBabelMinifier.processFilesForBundle
(packages/minifyStdJS/plugin/minify-js.js:118:9)
```

**Comment by arcthur** [comment]
I fix the error on 1.0.2

**Comment by LittleColin** [comment]
Is it worth keeping this issue open until 1.0.2 is available on npm?

**Comment by arcthur** [comment]
I published right now, please check the version.
