### ISSUE TITLE
Repeated calls to `setState``

### ISSUE THREAD

**Issue by daveisfera** [recharts/react-smooth#31]
We updated `react-smooth` from 1.0.2 to 1.0.5 and started getting this error with treemaps:
```
Uncaught Invariant Violation: Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
    at vendors.js:54289:28
    at checkForNestedUpdates (vendors.js:54292:7)
    at scheduleUpdateOnFiber (vendors.js:52563:3)
    at Object.enqueueSetState (vendors.js:44274:5)
    at Animate.Component.setState (vendors.js:71455:16)
    at Animate.componentDidUpdate (vendors.js:59325:14)
    at commitLifeCycles (vendors.js:51238:22)
    at commitLayoutEffects (vendors.js:53987:7)
    at HTMLUnknownElement.callCallback (vendors.js:31521:14)
    at Object.invokeGuardedCallbackDev (vendors.js:31571:16)
```

**Comment by ckifer** [comment]
This should be fixed after 1.0.6

https://github.com/recharts/react-smooth/pull/41
